### ISSUE TITLE
Build Command

### ISSUE THREAD

**Issue by EMJB** [DrGeoff/cec_simplest#1]
The command in the "build.sh" file and in the one in the comments at the top of the "cpp" file are different. Only the former works for me on my Pi1 with libcec version 3.0.1. - have yet to try it on my Pi2.

**Comment by DrGeoff** [comment]
Fixed.

I've harmonized the build commands.  I've also fixed a compile issue.

Could you git pull and let me know of any issues?

Thanks,
Geoff

**Comment by EMJB** [comment]
Had a quick look, and:

```
 (1) "-ldl" still seems to be missing from the version in the .cpp 
```

comments. Perhaps erroneously, I had attributed my compilation error to this

```
  (2) "-g4.8" is now missing from both - no idea whether this is 
```

important, but I think it is needed for compiling libcec itself.

but sorry I may not be in a position to try a new version for a couple 
of days.

Regards,

EMJB

**Comment by EMJB** [comment]
Further to my previous email, have managed to give the build file a 
quick try with the old cpp file- the "-4.8" appears to be optional, but 
the "-ldl" to be essential when run on a Pi1, but haven't had a chance t 
try on a Pi2 yet - have some other problems on that getting in the way.

Regards,

EMJB

**Comment by DrGeoff** [comment]
Hi EMJB,

I've pushed a new build.sh that just grabs the example build command out of the cpp file.  The two can never be out of sync now.  And thanks for noting that one had -ldl and the other didn't.  Yes it is necessary and that is also fixed.

Best wishes,
Geoff

**Comment by EMJB** [comment]
Thanks,

EMJB
