### ISSUE TITLE
sits there with a flashing cursor no output from TV remote

### ISSUE THREAD

**Issue by Electrik-rich546456** [DrGeoff/cec_simplest#3]
Hi, I see you closed the last issue... But it still does nothing when I press keys on the TV remote.
If it suppose to display info on the CLI as keys are pressed then why is it not showing up (up, down, left, right, red, green ....) 

what line can i get it to print something to show its working and to work out why my TV is not playing nice?

**Comment by DrGeoff** [comment]
Line 41 is where screen printed output should currently occur

**Comment by DrGeoff** [comment]
Not all HDMI cables are created equally.  You need one that advertises it has an audio return channel.

**Comment by Electrik-rich546456** [comment]
There is nothing wrong with my hardware as far as I know. It works with cec
client so why not with your one...? 🙂

**Comment by Electrik-rich546456** [comment]
Ok this is really strange.... It has started working unexpectedly. it seems the program takes a minute or two to settle down and connect to USB I guess. I'm now receiving messages from my TV remote. the strange thing is if i press any button once it shows up twice so for eg i press the red (old teletext button) once and i see `on_keypress: 114 ` twice. 
Whats that all about ?
Should it not read key down key up?

**Comment by DrGeoff** [comment]
I'm glad it is working for you.  I think the double output is exactly as
you said, Keydown and keyup, but it's been a while since I looked at the
CEC API.

**Comment by Electrik-rich546456** [comment]
well I've owned this device for a long long time and would really like to be able to use it for my idea but I think I've been climbing mount stupid rather that the CEC mountain lol.
Do you know what sort of area i should be learning to be able to do what i want in C ??

**Comment by Electrik-rich546456** [comment]
oh yeah is there a way to make it only print only one not twice as it doesn't do it with all keys ?????
arrrgggg I'm either bagging head on a Python wall  and now a C wall. :-(
```
on_keypress: 114 
on_keypress: 114 
on_keypress: 115 
on_keypress: 115 
on_keypress: 116 
on_keypress: 116 
on_keypress: 113 
on_keypress: 113 
on_keypress: 1 up
on_keypress: 4 right
on_keypress: 2 down
on_keypress: 3 left
on_keypress: 0 select
on_keypress: 0 select
on_keypress: 114 
on_keypress: 114 
on_keypress: 115 
on_keypress: 115 
on_keypress: 116 
on_keypress: 116 
on_keypress: 113 
on_keypress: 0 select
on_keypress: 0 select
on_keypress: 1 up
on_keypress: 2 down
on_keypress: 4 right
on_keypress: 3 left
```

**Comment by DrGeoff** [comment]
static unsigned long counter = 0;
    // There seems to be a "down" keypress and and "up" keypress
    // Make life simple by just swallowing the "up"
    if( counter++ % 2 ){ return; }

There's a snippet that I sometimes use to swallow the second event.  It
would be better to ensure that the consecutive messages are the same but
the above is simple.

If you want to write a program in C++  then it will take you about 100
hours to get a basic handle on the language.  C++ is more feature full than
C and if you are familiar with another language like Java or Python then
C++ will be easier to learn.   But the greater scope of the C++ language
will mean it will take longer than C to get your head around. The internet
is full of resources on how to learn any language you want to.  But the
advantage a book has is that somebody has curated it.

Best wishes,
Geoff
